export const KEYBOARD_ROWS = [
  [
    { id: 'backtick', key: '`', code: 'Backquote' },
    { id: '1', key: '1', code: 'Digit1' },
    { id: '2', key: '2', code: 'Digit2' },
    { id: '3', key: '3', code: 'Digit3' },
    { id: '4', key: '4', code: 'Digit4' },
    { id: '5', key: '5', code: 'Digit5' },
    { id: '6', key: '6', code: 'Digit6' },
    { id: '7', key: '7', code: 'Digit7' },
    { id: '8', key: '8', code: 'Digit8' },
    { id: '9', key: '9', code: 'Digit9' },
    { id: '0', key: '0', code: 'Digit0' },
    { id: 'minus', key: '-', code: 'Minus' },
    { id: 'equal', key: '=', code: 'Equal' },
    { id: 'backspace', key: 'Backspace', code: 'Backspace' },
  ],
  [
    { id: 'tab', key: 'Tab', code: 'Tab' },
    { id: 'q', key: 'q', code: 'KeyQ' },
    { id: 'w', key: 'w', code: 'KeyW' },
    { id: 'e', key: 'e', code: 'KeyE' },
    { id: 'r', key: 'r', code: 'KeyR' },
    { id: 't', key: 't', code: 'KeyT' },
    { id: 'y', key: 'y', code: 'KeyY' },
    { id: 'u', key: 'u', code: 'KeyU' },
    { id: 'i', key: 'i', code: 'KeyI' },
    { id: 'o', key: 'o', code: 'KeyO' },
    { id: 'p', key: 'p', code: 'KeyP' },
    { id: 'left_bracket', key: '[', code: 'BracketLeft' },
    { id: 'right_bracket', key: ']', code: 'BracketRight' },
    { id: 'backslash', key: '\\', code: 'Backslash' },
  ],
  [
    { id: 'caps_lock', key: 'Caps Lock', code: 'CapsLock' },
    { id: 'a', key: 'a', code: 'KeyA' },
    { id: 's', key: 's', code: 'KeyS' },
    { id: 'd', key: 'd', code: 'KeyD' },
    { id: 'f', key: 'f', code: 'KeyF' },
    { id: 'g', key: 'g', code: 'KeyG' },
    { id: 'h', key: 'h', code: 'KeyH' },
    { id: 'j', key: 'j', code: 'KeyJ' },
    { id: 'k', key: 'k', code: 'KeyK' },
    { id: 'l', key: 'l', code: 'KeyL' },
    { id: 'semicolon', key: ';', code: 'Semicolon' },
    { id: 'quote', key: "'", code: 'Quote' },
    { id: 'enter', key: 'Enter', code: 'Enter' },
  ],
  [
    { id: 'left_shift', key: 'Shift', code: 'ShiftLeft' },
    { id: 'z', key: 'z', code: 'KeyZ' },
    { id: 'x', key: 'x', code: 'KeyX' },
    { id: 'c', key: 'c', code: 'KeyC' },
    { id: 'v', key: 'v', code: 'KeyV' },
    { id: 'b', key: 'b', code: 'KeyB' },
    { id: 'n', key: 'n', code: 'KeyN' },
    { id: 'm', key: 'm', code: 'KeyM' },
    { id: 'comma', key: ',', code: 'Comma' },
    { id: 'period', key: '.', code: 'Period' },
    { id: 'slash', key: '/', code: 'Slash' },
    { id: 'right_shift', key: 'Shift', code: 'ShiftRight' },
  ],
  [
    { id: 'left_ctrl', key: 'Ctrl', code: 'ControlLeft' },
    { id: 'left_alt', key: 'Alt', code: 'AltLeft' },
    { id: 'space', key: '&nbsp;', code: 'Space' },
    { id: 'right_alt', key: 'Alt', code: 'AltRight' },
    { id: 'right_ctrl', key: 'Ctrl', code: 'ControlRight' },
  ],
];

export const NON_PRINTABLE_KEYS = new Set([
  'AltLeft',
  'AltRight',
  'CapsLock',
  'ControlLeft',
  'ControlRight',
  'Enter',
  'ShiftLeft',
  'ShiftRight',
  'Tab',
]);
